import type {
  AlertDTO,
  HistoryPoint,
  IntervalStats,
  NationalStats,
  StationDTO,
  StationKind,
} from "../../../shared/src/index.js";
import {
  categoryFromScore,
  explainRisk,
  sanitizeRateOfRise,
  type LevelBasis,
} from "../../../shared/src/index.js";

const now = Date.now();

export const FALLBACK_STATIONS: StationDTO[] = [
  {
    id: "fb-brahmaputra",
    externalId: "brahmaputra-guwahati",
    source: "demo",
    sourceLabel: "Simulated",
    simulated: true,
    name: "Brahmaputra at Guwahati",
    kind: "River" as StationKind,
    place: "Guwahati, Assam",
    region: "Assam",
    lat: 26.1844,
    lng: 91.7361,
    unit: "m",
    levelBasis: "Depth" as LevelBasis,
    normalLevel: 46.0,
    warningLevel: 48.5,
    dangerLevel: 49.5,
    riskConfig: {
      weightProximity: 60,
      weightRise: 30,
      weightRain: 10,
      riseNormDivisor: 0.06,
      rainfallEnabled: true,
      alertCooldownMin: 15,
    },
    latest: {
      level: 48.72,
      unit: "m",
      riskScore: 78,
      category: "Severe",
      rateOfRise: 0.12,
      rainfallMm: 18.5,
      observedAt: new Date(now - 8 * 60_000).toISOString(),
      projection: {
        hoursToWarning: 0,
        hoursToDanger: 6.5,
      },
      explain: explainRisk({
        proximity: 0.77,
        riseNorm: 0.8,
        rainfallNorm: 0.185,
        weights: { proximity: 60, rise: 30, rain: 10 },
      }),
    },
    recent: Array.from({ length: 24 }).map((_, i) => ({
      t: now - (23 - i) * 3600_000,
      v: Math.round((47.2 + (i / 23) * 1.52) * 100) / 100,
    })),
  },
  {
    id: "fb-ganga-patna",
    externalId: "ganga-patna",
    source: "demo",
    sourceLabel: "Simulated",
    simulated: true,
    name: "Ganga at Patna",
    kind: "River" as StationKind,
    place: "Patna, Bihar",
    region: "Bihar",
    lat: 25.5941,
    lng: 85.1376,
    unit: "m",
    levelBasis: "Depth" as LevelBasis,
    normalLevel: 46.5,
    warningLevel: 49.0,
    dangerLevel: 50.0,
    riskConfig: {
      weightProximity: 60,
      weightRise: 30,
      weightRain: 10,
      riseNormDivisor: 0.06,
      rainfallEnabled: false,
      alertCooldownMin: 30,
    },
    latest: {
      level: 47.85,
      unit: "m",
      riskScore: 42,
      category: "Watch",
      rateOfRise: 0.04,
      rainfallMm: null,
      observedAt: new Date(now - 12 * 60_000).toISOString(),
      projection: {
        hoursToWarning: 28.7,
        hoursToDanger: 53.7,
      },
      explain: explainRisk({
        proximity: 0.385,
        riseNorm: 0.38,
        rainfallNorm: 0,
        weights: { proximity: 60, rise: 30, rain: 10 },
      }),
    },
    recent: Array.from({ length: 24 }).map((_, i) => ({
      t: now - (23 - i) * 3600_000,
      v: Math.round((47.1 + (i / 23) * 0.75) * 100) / 100,
    })),
  },
  {
    id: "fb-godavari-polavaram",
    externalId: "godavari-polavaram",
    source: "demo",
    sourceLabel: "Simulated",
    simulated: true,
    name: "Godavari at Polavaram (Dam)",
    kind: "Dam" as StationKind,
    place: "West Godavari, Andhra Pradesh",
    region: "Andhra Pradesh",
    lat: 17.2458,
    lng: 81.6453,
    unit: "m",
    levelBasis: "Depth" as LevelBasis,
    normalLevel: 37.5,
    warningLevel: 39.5,
    dangerLevel: 41.0,
    riskConfig: {
      weightProximity: 60,
      weightRise: 30,
      weightRain: 10,
      riseNormDivisor: 0.08,
      rainfallEnabled: false,
      alertCooldownMin: 30,
    },
    latest: {
      level: 38.2,
      unit: "m",
      riskScore: 22,
      category: "Normal",
      rateOfRise: 0.01,
      rainfallMm: null,
      observedAt: new Date(now - 15 * 60_000).toISOString(),
      projection: null,
      explain: explainRisk({
        proximity: 0.2,
        riseNorm: 0.1,
        rainfallNorm: 0,
        weights: { proximity: 60, rise: 30, rain: 10 },
      }),
    },
    recent: Array.from({ length: 24 }).map((_, i) => ({
      t: now - (23 - i) * 3600_000,
      v: Math.round((37.8 + Math.sin(i / 3) * 0.4) * 100) / 100,
    })),
  },
  {
    id: "fb-mahanadi-naraj",
    externalId: "mahanadi-naraj",
    source: "demo",
    sourceLabel: "Simulated",
    simulated: true,
    name: "Mahanadi at Naraj",
    kind: "River" as StationKind,
    place: "Cuttack, Odisha",
    region: "Odisha",
    lat: 20.4636,
    lng: 85.7353,
    unit: "m",
    levelBasis: "Depth" as LevelBasis,
    normalLevel: 19.0,
    warningLevel: 21.5,
    dangerLevel: 22.5,
    riskConfig: {
      weightProximity: 60,
      weightRise: 30,
      weightRain: 10,
      riseNormDivisor: 0.06,
      rainfallEnabled: false,
      alertCooldownMin: 30,
    },
    latest: {
      level: 19.85,
      unit: "m",
      riskScore: 25,
      category: "Normal",
      rateOfRise: 0.02,
      rainfallMm: null,
      observedAt: new Date(now - 20 * 60_000).toISOString(),
      projection: null,
      explain: explainRisk({
        proximity: 0.24,
        riseNorm: 0.15,
        rainfallNorm: 0,
        weights: { proximity: 60, rise: 30, rain: 10 },
      }),
    },
    recent: Array.from({ length: 24 }).map((_, i) => ({
      t: now - (23 - i) * 3600_000,
      v: Math.round((19.3 + Math.sin(i / 4) * 0.5) * 100) / 100,
    })),
  },
  {
    id: "fb-teesta-domohani",
    externalId: "teesta-domohani",
    source: "demo",
    sourceLabel: "Simulated",
    simulated: true,
    name: "Teesta at Domohani (Hill River)",
    kind: "River" as StationKind,
    place: "Jalpaiguri, West Bengal",
    region: "West Bengal",
    lat: 26.7597,
    lng: 88.7414,
    unit: "m",
    levelBasis: "Depth" as LevelBasis,
    normalLevel: 88.0,
    warningLevel: 89.8,
    dangerLevel: 90.5,
    riskConfig: {
      weightProximity: 60,
      weightRise: 30,
      weightRain: 10,
      riseNormDivisor: 0.1,
      rainfallEnabled: false,
      alertCooldownMin: 20,
    },
    latest: {
      level: 89.4,
      unit: "m",
      riskScore: 56,
      category: "Warning",
      rateOfRise: 0.08,
      rainfallMm: null,
      observedAt: new Date(now - 10 * 60_000).toISOString(),
      projection: {
        hoursToWarning: 0,
        hoursToDanger: 13.7,
      },
      explain: explainRisk({
        proximity: 0.56,
        riseNorm: 0.32,
        rainfallNorm: 0,
        weights: { proximity: 60, rise: 30, rain: 10 },
      }),
    },
    recent: Array.from({ length: 24 }).map((_, i) => ({
      t: now - (23 - i) * 3600_000,
      v: Math.round((88.6 + (i / 23) * 0.8) * 100) / 100,
    })),
  },
];

export const FALLBACK_ALERTS: AlertDTO[] = [
  {
    id: "alert-fb-001",
    stationId: "fb-brahmaputra",
    stationName: "Brahmaputra at Guwahati",
    place: "Guwahati, Assam",
    kind: "River",
    riskScore: 78,
    category: "Severe",
    channel: "email",
    sentTo: "ndrf@demo.local",
    body: "HDNS FLOOD ALERT — SEVERE (78/100)\nStation: Brahmaputra at Guwahati (Guwahati, Assam)\nLevel: 48.72 m | rise +0.12 m/h\nThresholds: warning 48.5 / danger 49.5 m\nStill rising — ~6.5h to danger level (linear estimate).\n──\nSent to a DEMO distribution list (not NDRF/NDMA). Acknowledge in the HDNS authority console.",
    delivered: true,
    deliveredVia: "console-demo",
    deliveryState: "logged-console",
    createdAt: new Date(now - 14 * 60_000).toISOString(),
    acknowledgedAt: null,
    acknowledgedBy: null,
    level: 48.72,
    unit: "m",
    normalLevel: 46.0,
    warningLevel: 48.5,
    dangerLevel: 49.5,
    rateOfRise: 0.12,
    projectionHoursToWarning: 0,
    projectionHoursToDanger: 6.5,
  },
  {
    id: "alert-fb-002",
    stationId: "fb-teesta-domohani",
    stationName: "Teesta at Domohani (Hill River)",
    place: "Jalpaiguri, West Bengal",
    kind: "River",
    riskScore: 56,
    category: "Warning",
    channel: "sms",
    sentTo: "+91-DEMO-CONTROL",
    body: "HDNS FLOOD ALERT — WARNING (56/100)\nStation: Teesta at Domohani\nLevel: 89.4 m | rise +0.08 m/h\nThresholds: warning 89.8 / danger 90.5 m\nStill rising — ~13.7h to danger level.\n──\nSent to DEMO list.",
    delivered: true,
    deliveredVia: "console-demo",
    deliveryState: "logged-console",
    createdAt: new Date(now - 32 * 60_000).toISOString(),
    acknowledgedAt: new Date(now - 10 * 60_000).toISOString(),
    acknowledgedBy: "NDRF Control Room (Demo)",
    level: 89.4,
    unit: "m",
    normalLevel: 88.0,
    warningLevel: 89.8,
    dangerLevel: 90.5,
    rateOfRise: 0.08,
    projectionHoursToWarning: 0,
    projectionHoursToDanger: 13.7,
  },
];

export function getFallbackStats(): NationalStats {
  const scores = FALLBACK_STATIONS.map((s) => s.latest?.riskScore ?? 0);
  const byCategory = {
    Normal: 2,
    Watch: 1,
    Warning: 1,
    Severe: 1,
    Critical: 0,
    "No data": 0,
  };
  return {
    nationalIndex: Math.round(scores.reduce((a, b) => a + b, 0) / scores.length),
    totalStations: FALLBACK_STATIONS.length,
    withReadings: FALLBACK_STATIONS.length,
    byCategory,
    updatedAt: new Date().toISOString(),
  };
}

export function getFallbackHistory(stationId: string, hours = 24): { points: HistoryPoint[]; stats: IntervalStats } {
  const st = FALLBACK_STATIONS.find((s) => s.id === stationId) ?? FALLBACK_STATIONS[0];
  const count = Math.min(hours, 48);
  const stepMs = (hours * 3600_000) / count;
  const points: HistoryPoint[] = Array.from({ length: count }).map((_, i) => {
    const t = now - (count - 1 - i) * stepMs;
    const v = Math.round((st.normalLevel + (i / count) * (st.latest?.level ? st.latest.level - st.normalLevel : 1)) * 100) / 100;
    const score = Math.round(20 + (i / count) * 45);
    return {
      t,
      v,
      riskScore: score,
      category: categoryFromScore(score),
    };
  });
  const vals = points.map((p) => p.v);
  return {
    points,
    stats: {
      label: `Last ${hours}h`,
      rateOfRise: st.latest?.rateOfRise ?? 0.05,
      min: Math.min(...vals),
      max: Math.max(...vals),
      avg: Math.round((vals.reduce((a, b) => a + b, 0) / vals.length) * 100) / 100,
      current: st.latest?.level ?? st.normalLevel,
      category: st.latest?.category ?? "Normal",
    },
  };
}
