import type {
  AlertDTO,
  HistoryPoint,
  IntervalStats,
  NationalStats,
  StationDTO,
  StationKind,
} from "../../../shared/src/index.js";
import {
  categoryFromScore,
  explainRisk,
  type LevelBasis,
} from "../../../shared/src/index.js";

const now = Date.now();

export const FALLBACK_STATIONS: StationDTO[] = [
  // ── 6 REAL NWDP / CWC TELEMETRY STATIONS ────────────────────────────────
  {
    id: "nwdp-arrah-chhapra-bridge",
    externalId: "nwdp-arrah-chhapra-bridge",
    source: "nwdp",
    sourceLabel: "INDIA · NWDP",
    simulated: false,
    name: "Ganga at Arrah Chhapra Bridge",
    kind: "River" as StationKind,
    place: "Saran, Bihar · Bihar Water Dept",
    region: "Bihar",
    lat: 25.71666667,
    lng: 84.81166667,
    unit: "m",
    levelBasis: "Depth" as LevelBasis,
    normalLevel: 45.07,
    warningLevel: 48.44,
    dangerLevel: 51.8,
    riskConfig: {
      weightProximity: 60,
      weightRise: 30,
      weightRain: 10,
      riseNormDivisor: 0.06,
      rainfallEnabled: false,
      alertCooldownMin: 30,
    },
    latest: {
      level: 49.12,
      unit: "m",
      riskScore: 64,
      category: "Warning",
      rateOfRise: 0.075,
      rainfallMm: null,
      observedAt: new Date(now - 10 * 60_000).toISOString(),
      projection: {
        hoursToWarning: 0,
        hoursToDanger: 35.7,
      },
      explain: explainRisk({
        proximity: 0.601,
        riseNorm: 0.37,
        rainfallNorm: 0,
        weights: { proximity: 60, rise: 30, rain: 10 },
      }),
    },
    recent: Array.from({ length: 24 }).map((_, i) => ({
      t: now - (23 - i) * 3600_000,
      v: Math.round((48.1 + (i / 23) * 1.02) * 100) / 100,
    })),
  },
  {
    id: "nwdp-nh15-crossing-fakirpara-tangni",
    externalId: "nwdp-nh15-crossing-fakirpara-tangni",
    source: "nwdp",
    sourceLabel: "INDIA · NWDP",
    simulated: false,
    name: "Brahmaputra at NH-15 Fakirpara Tangni",
    kind: "River" as StationKind,
    place: "Darrang, Assam · Assam Water Dept",
    region: "Assam",
    lat: 26.50833333,
    lng: 92.11638889,
    unit: "m",
    levelBasis: "Depth" as LevelBasis,
    normalLevel: 60.6,
    warningLevel: 61.11,
    dangerLevel: 61.62,
    riskConfig: {
      weightProximity: 60,
      weightRise: 30,
      weightRain: 10,
      riseNormDivisor: 0.06,
      rainfallEnabled: false,
      alertCooldownMin: 30,
    },
    latest: {
      level: 60.98,
      unit: "m",
      riskScore: 44,
      category: "Watch",
      rateOfRise: 0.04,
      rainfallMm: null,
      observedAt: new Date(now - 15 * 60_000).toISOString(),
      projection: {
        hoursToWarning: 3.25,
        hoursToDanger: 16.0,
      },
      explain: explainRisk({
        proximity: 0.372,
        riseNorm: 0.39,
        rainfallNorm: 0,
        weights: { proximity: 60, rise: 30, rain: 10 },
      }),
    },
    recent: Array.from({ length: 24 }).map((_, i) => ({
      t: now - (23 - i) * 3600_000,
      v: Math.round((60.65 + (i / 23) * 0.33) * 100) / 100,
    })),
  },
  {
    id: "nwdp-bhadrachalam",
    externalId: "nwdp-bhadrachalam",
    source: "nwdp",
    sourceLabel: "INDIA · NWDP",
    simulated: false,
    name: "Godavari at Bhadrachalam",
    kind: "River" as StationKind,
    place: "Bhadradri Kothagudem, Telangana · CWC",
    region: "Telangana",
    lat: 17.66944444,
    lng: 80.87388889,
    unit: "m",
    levelBasis: "Depth" as LevelBasis,
    normalLevel: 39.13,
    warningLevel: 42.93,
    dangerLevel: 46.72,
    riskConfig: {
      weightProximity: 60,
      weightRise: 30,
      weightRain: 10,
      riseNormDivisor: 0.06,
      rainfallEnabled: false,
      alertCooldownMin: 30,
    },
    latest: {
      level: 40.15,
      unit: "m",
      riskScore: 22,
      category: "Normal",
      rateOfRise: 0.015,
      rainfallMm: null,
      observedAt: new Date(now - 20 * 60_000).toISOString(),
      projection: null,
      explain: explainRisk({
        proximity: 0.134,
        riseNorm: 0.1,
        rainfallNorm: 0,
        weights: { proximity: 60, rise: 30, rain: 10 },
      }),
    },
    recent: Array.from({ length: 24 }).map((_, i) => ({
      t: now - (23 - i) * 3600_000,
      v: Math.round((39.4 + Math.sin(i / 4) * 0.5) * 100) / 100,
    })),
  },
  {
    id: "nwdp-ambabal-narangi",
    externalId: "nwdp-ambabal-narangi",
    source: "nwdp",
    sourceLabel: "INDIA · NWDP",
    simulated: false,
    name: "Godavari at Ambabal (Narangi)",
    kind: "River" as StationKind,
    place: "Bastar, Chhattisgarh · CWC",
    region: "Chhattisgarh",
    lat: 19.29666667,
    lng: 81.78888889,
    unit: "m",
    levelBasis: "RL" as LevelBasis,
    normalLevel: 535.06,
    warningLevel: 535.71,
    dangerLevel: 536.36,
    riskConfig: {
      weightProximity: 60,
      weightRise: 30,
      weightRain: 10,
      riseNormDivisor: 0.06,
      rainfallEnabled: false,
      alertCooldownMin: 30,
    },
    latest: {
      level: 535.28,
      unit: "m",
      riskScore: 23,
      category: "Normal",
      rateOfRise: 0.01,
      rainfallMm: null,
      observedAt: new Date(now - 25 * 60_000).toISOString(),
      projection: null,
      explain: explainRisk({
        proximity: 0.169,
        riseNorm: 0.12,
        rainfallNorm: 0,
        weights: { proximity: 60, rise: 30, rain: 10 },
      }),
    },
    recent: Array.from({ length: 24 }).map((_, i) => ({
      t: now - (23 - i) * 3600_000,
      v: Math.round((535.1 + Math.sin(i / 3) * 0.15) * 100) / 100,
    })),
  },
  {
    id: "nwdp-koida",
    externalId: "nwdp-koida",
    source: "nwdp",
    sourceLabel: "INDIA · NWDP",
    simulated: false,
    name: "Godavari at Koida",
    kind: "River" as StationKind,
    place: "Eluru, Andhra Pradesh · CWC",
    region: "Andhra Pradesh",
    lat: 17.4825,
    lng: 81.38666667,
    unit: "m",
    levelBasis: "Depth" as LevelBasis,
    normalLevel: 22.36,
    warningLevel: 23.01,
    dangerLevel: 23.66,
    riskConfig: {
      weightProximity: 60,
      weightRise: 30,
      weightRain: 10,
      riseNormDivisor: 0.06,
      rainfallEnabled: false,
      alertCooldownMin: 30,
    },
    latest: {
      level: 22.58,
      unit: "m",
      riskScore: 22,
      category: "Normal",
      rateOfRise: 0.012,
      rainfallMm: null,
      observedAt: new Date(now - 30 * 60_000).toISOString(),
      projection: null,
      explain: explainRisk({
        proximity: 0.169,
        riseNorm: 0.15,
        rainfallNorm: 0,
        weights: { proximity: 60, rise: 30, rain: 10 },
      }),
    },
    recent: Array.from({ length: 24 }).map((_, i) => ({
      t: now - (23 - i) * 3600_000,
      v: Math.round((22.42 + Math.sin(i / 5) * 0.18) * 100) / 100,
    })),
  },
  {
    id: "nwdp-baisi-1",
    externalId: "nwdp-baisi-1",
    source: "nwdp",
    sourceLabel: "INDIA · NWDP",
    simulated: false,
    name: "Ganga at Baisi",
    kind: "River" as StationKind,
    place: "Purnia, Bihar · Bihar Water Dept",
    region: "Bihar",
    lat: 25.86277778,
    lng: 87.73888889,
    unit: "m",
    levelBasis: "Depth" as LevelBasis,
    normalLevel: 33.39,
    warningLevel: 33.8,
    dangerLevel: 34.2,
    riskConfig: {
      weightProximity: 60,
      weightRise: 30,
      weightRain: 10,
      riseNormDivisor: 0.06,
      rainfallEnabled: false,
      alertCooldownMin: 30,
    },
    latest: {
      level: 33.52,
      unit: "m",
      riskScore: 21,
      category: "Normal",
      rateOfRise: 0.01,
      rainfallMm: null,
      observedAt: new Date(now - 18 * 60_000).toISOString(),
      projection: null,
      explain: explainRisk({
        proximity: 0.16,
        riseNorm: 0.1,
        rainfallNorm: 0,
        weights: { proximity: 60, rise: 30, rain: 10 },
      }),
    },
    recent: Array.from({ length: 24 }).map((_, i) => ({
      t: now - (23 - i) * 3600_000,
      v: Math.round((33.42 + Math.sin(i / 4) * 0.12) * 100) / 100,
    })),
  },

  // ── 6 SIMULATED INDIAN ALERT SCENARIOS ──────────────────────────────────
  {
    id: "fb-brahmaputra",
    externalId: "brahmaputra-guwahati",
    source: "demo",
    sourceLabel: "Simulated",
    simulated: true,
    name: "Brahmaputra at Guwahati",
    kind: "River" as StationKind,
    place: "Guwahati, Assam",
    region: "Assam",
    lat: 26.1844,
    lng: 91.7361,
    unit: "m",
    levelBasis: "Depth" as LevelBasis,
    normalLevel: 46.0,
    warningLevel: 48.5,
    dangerLevel: 49.5,
    riskConfig: {
      weightProximity: 60,
      weightRise: 30,
      weightRain: 10,
      riseNormDivisor: 0.06,
      rainfallEnabled: true,
      alertCooldownMin: 15,
    },
    latest: {
      level: 48.72,
      unit: "m",
      riskScore: 78,
      category: "Severe",
      rateOfRise: 0.12,
      rainfallMm: 18.5,
      observedAt: new Date(now - 8 * 60_000).toISOString(),
      projection: {
        hoursToWarning: 0,
        hoursToDanger: 6.5,
      },
      explain: explainRisk({
        proximity: 0.77,
        riseNorm: 0.8,
        rainfallNorm: 0.185,
        weights: { proximity: 60, rise: 30, rain: 10 },
      }),
    },
    recent: Array.from({ length: 24 }).map((_, i) => ({
      t: now - (23 - i) * 3600_000,
      v: Math.round((47.2 + (i / 23) * 1.52) * 100) / 100,
    })),
  },
  {
    id: "fb-ganga-patna",
    externalId: "ganga-patna",
    source: "demo",
    sourceLabel: "Simulated",
    simulated: true,
    name: "Ganga at Patna",
    kind: "River" as StationKind,
    place: "Patna, Bihar",
    region: "Bihar",
    lat: 25.5941,
    lng: 85.1376,
    unit: "m",
    levelBasis: "Depth" as LevelBasis,
    normalLevel: 46.5,
    warningLevel: 49.0,
    dangerLevel: 50.0,
    riskConfig: {
      weightProximity: 60,
      weightRise: 30,
      weightRain: 10,
      riseNormDivisor: 0.06,
      rainfallEnabled: false,
      alertCooldownMin: 30,
    },
    latest: {
      level: 47.85,
      unit: "m",
      riskScore: 42,
      category: "Watch",
      rateOfRise: 0.04,
      rainfallMm: null,
      observedAt: new Date(now - 12 * 60_000).toISOString(),
      projection: {
        hoursToWarning: 28.7,
        hoursToDanger: 53.7,
      },
      explain: explainRisk({
        proximity: 0.385,
        riseNorm: 0.38,
        rainfallNorm: 0,
        weights: { proximity: 60, rise: 30, rain: 10 },
      }),
    },
    recent: Array.from({ length: 24 }).map((_, i) => ({
      t: now - (23 - i) * 3600_000,
      v: Math.round((47.1 + (i / 23) * 0.75) * 100) / 100,
    })),
  },
  {
    id: "fb-godavari-polavaram",
    externalId: "godavari-polavaram",
    source: "demo",
    sourceLabel: "Simulated",
    simulated: true,
    name: "Godavari at Polavaram (Dam)",
    kind: "Dam" as StationKind,
    place: "West Godavari, Andhra Pradesh",
    region: "Andhra Pradesh",
    lat: 17.2458,
    lng: 81.6453,
    unit: "m",
    levelBasis: "Depth" as LevelBasis,
    normalLevel: 37.5,
    warningLevel: 39.5,
    dangerLevel: 41.0,
    riskConfig: {
      weightProximity: 60,
      weightRise: 30,
      weightRain: 10,
      riseNormDivisor: 0.08,
      rainfallEnabled: false,
      alertCooldownMin: 30,
    },
    latest: {
      level: 38.2,
      unit: "m",
      riskScore: 22,
      category: "Normal",
      rateOfRise: 0.01,
      rainfallMm: null,
      observedAt: new Date(now - 15 * 60_000).toISOString(),
      projection: null,
      explain: explainRisk({
        proximity: 0.2,
        riseNorm: 0.1,
        rainfallNorm: 0,
        weights: { proximity: 60, rise: 30, rain: 10 },
      }),
    },
    recent: Array.from({ length: 24 }).map((_, i) => ({
      t: now - (23 - i) * 3600_000,
      v: Math.round((37.8 + Math.sin(i / 3) * 0.4) * 100) / 100,
    })),
  },
  {
    id: "fb-krishna-vijayawada",
    externalId: "krishna-vijayawada",
    source: "demo",
    sourceLabel: "Simulated",
    simulated: true,
    name: "Krishna at Vijayawada",
    kind: "River" as StationKind,
    place: "Vijayawada, Andhra Pradesh",
    region: "Andhra Pradesh",
    lat: 16.5224,
    lng: 80.6236,
    unit: "m",
    levelBasis: "Depth" as LevelBasis,
    normalLevel: 14.5,
    warningLevel: 16.5,
    dangerLevel: 17.5,
    riskConfig: {
      weightProximity: 60,
      weightRise: 30,
      weightRain: 10,
      riseNormDivisor: 0.06,
      rainfallEnabled: false,
      alertCooldownMin: 30,
    },
    latest: {
      level: 15.1,
      unit: "m",
      riskScore: 24,
      category: "Normal",
      rateOfRise: 0.015,
      rainfallMm: null,
      observedAt: new Date(now - 14 * 60_000).toISOString(),
      projection: null,
      explain: explainRisk({
        proximity: 0.2,
        riseNorm: 0.12,
        rainfallNorm: 0,
        weights: { proximity: 60, rise: 30, rain: 10 },
      }),
    },
    recent: Array.from({ length: 24 }).map((_, i) => ({
      t: now - (23 - i) * 3600_000,
      v: Math.round((14.8 + Math.sin(i / 4) * 0.3) * 100) / 100,
    })),
  },
  {
    id: "fb-mahanadi-naraj",
    externalId: "mahanadi-naraj",
    source: "demo",
    sourceLabel: "Simulated",
    simulated: true,
    name: "Mahanadi at Naraj",
    kind: "River" as StationKind,
    place: "Cuttack, Odisha",
    region: "Odisha",
    lat: 20.4636,
    lng: 85.7353,
    unit: "m",
    levelBasis: "Depth" as LevelBasis,
    normalLevel: 19.0,
    warningLevel: 21.5,
    dangerLevel: 22.5,
    riskConfig: {
      weightProximity: 60,
      weightRise: 30,
      weightRain: 10,
      riseNormDivisor: 0.06,
      rainfallEnabled: false,
      alertCooldownMin: 30,
    },
    latest: {
      level: 19.85,
      unit: "m",
      riskScore: 25,
      category: "Normal",
      rateOfRise: 0.02,
      rainfallMm: null,
      observedAt: new Date(now - 20 * 60_000).toISOString(),
      projection: null,
      explain: explainRisk({
        proximity: 0.24,
        riseNorm: 0.15,
        rainfallNorm: 0,
        weights: { proximity: 60, rise: 30, rain: 10 },
      }),
    },
    recent: Array.from({ length: 24 }).map((_, i) => ({
      t: now - (23 - i) * 3600_000,
      v: Math.round((19.3 + Math.sin(i / 4) * 0.5) * 100) / 100,
    })),
  },
  {
    id: "fb-teesta-domohani",
    externalId: "teesta-domohani",
    source: "demo",
    sourceLabel: "Simulated",
    simulated: true,
    name: "Teesta at Domohani (Hill River)",
    kind: "River" as StationKind,
    place: "Jalpaiguri, West Bengal",
    region: "West Bengal",
    lat: 26.7597,
    lng: 88.7414,
    unit: "m",
    levelBasis: "Depth" as LevelBasis,
    normalLevel: 88.0,
    warningLevel: 89.8,
    dangerLevel: 90.5,
    riskConfig: {
      weightProximity: 60,
      weightRise: 30,
      weightRain: 10,
      riseNormDivisor: 0.1,
      rainfallEnabled: false,
      alertCooldownMin: 20,
    },
    latest: {
      level: 89.4,
      unit: "m",
      riskScore: 56,
      category: "Warning",
      rateOfRise: 0.08,
      rainfallMm: null,
      observedAt: new Date(now - 10 * 60_000).toISOString(),
      projection: {
        hoursToWarning: 0,
        hoursToDanger: 13.7,
      },
      explain: explainRisk({
        proximity: 0.56,
        riseNorm: 0.32,
        rainfallNorm: 0,
        weights: { proximity: 60, rise: 30, rain: 10 },
      }),
    },
    recent: Array.from({ length: 24 }).map((_, i) => ({
      t: now - (23 - i) * 3600_000,
      v: Math.round((88.6 + (i / 23) * 0.8) * 100) / 100,
    })),
  },

  // ── UK ENVIRONMENT AGENCY REFERENCE GAUGES ─────────────────────────────
  {
    id: "uk-bourton-dickler",
    externalId: "1029TH",
    source: "ukEA",
    sourceLabel: "UK EA · live",
    simulated: false,
    name: "Bourton Dickler",
    kind: "River" as StationKind,
    place: "Little Rissington",
    region: "United Kingdom",
    lat: 51.874767,
    lng: -1.740083,
    unit: "m",
    levelBasis: "Depth" as LevelBasis,
    normalLevel: 0.15,
    warningLevel: 0.85,
    dangerLevel: 1.25,
    riskConfig: {
      weightProximity: 60,
      weightRise: 30,
      weightRain: 10,
      riseNormDivisor: 0.06,
      rainfallEnabled: false,
      alertCooldownMin: 30,
    },
    latest: {
      level: 0.28,
      unit: "m",
      riskScore: 15,
      category: "Normal",
      rateOfRise: 0.005,
      rainfallMm: null,
      observedAt: new Date(now - 5 * 60_000).toISOString(),
      projection: null,
      explain: explainRisk({
        proximity: 0.118,
        riseNorm: 0.08,
        rainfallNorm: 0,
        weights: { proximity: 60, rise: 30, rain: 10 },
      }),
    },
    recent: Array.from({ length: 24 }).map((_, i) => ({
      t: now - (23 - i) * 3600_000,
      v: Math.round((0.26 + Math.sin(i / 6) * 0.04) * 100) / 100,
    })),
  },
  {
    id: "uk-thames-reading",
    externalId: "1140TH",
    source: "ukEA",
    sourceLabel: "UK EA · live",
    simulated: false,
    name: "Thames at Reading",
    kind: "River" as StationKind,
    place: "Reading, Berkshire",
    region: "United Kingdom",
    lat: 51.4608,
    lng: -0.9701,
    unit: "m",
    levelBasis: "Depth" as LevelBasis,
    normalLevel: 1.2,
    warningLevel: 2.1,
    dangerLevel: 2.8,
    riskConfig: {
      weightProximity: 60,
      weightRise: 30,
      weightRain: 10,
      riseNormDivisor: 0.06,
      rainfallEnabled: false,
      alertCooldownMin: 30,
    },
    latest: {
      level: 1.45,
      unit: "m",
      riskScore: 18,
      category: "Normal",
      rateOfRise: 0.01,
      rainfallMm: null,
      observedAt: new Date(now - 10 * 60_000).toISOString(),
      projection: null,
      explain: explainRisk({
        proximity: 0.156,
        riseNorm: 0.1,
        rainfallNorm: 0,
        weights: { proximity: 60, rise: 30, rain: 10 },
      }),
    },
    recent: Array.from({ length: 24 }).map((_, i) => ({
      t: now - (23 - i) * 3600_000,
      v: Math.round((1.42 + Math.sin(i / 5) * 0.06) * 100) / 100,
    })),
  },
];

export const FALLBACK_ALERTS: AlertDTO[] = [
  {
    id: "alert-fb-001",
    stationId: "fb-brahmaputra",
    stationName: "Brahmaputra at Guwahati",
    place: "Guwahati, Assam",
    kind: "River",
    riskScore: 78,
    category: "Severe",
    channel: "email",
    sentTo: "ndrf@demo.local",
    body: "HDNS FLOOD ALERT — SEVERE (78/100)\nStation: Brahmaputra at Guwahati (Guwahati, Assam)\nLevel: 48.72 m | rise +0.12 m/h\nThresholds: warning 48.5 / danger 49.5 m\nStill rising — ~6.5h to danger level (linear estimate).\n──\nSent to a DEMO distribution list (not NDRF/NDMA). Acknowledge in the HDNS authority console.",
    delivered: true,
    deliveredVia: "console-demo",
    deliveryState: "logged-console",
    createdAt: new Date(now - 14 * 60_000).toISOString(),
    acknowledgedAt: null,
    acknowledgedBy: null,
    level: 48.72,
    unit: "m",
    normalLevel: 46.0,
    warningLevel: 48.5,
    dangerLevel: 49.5,
    rateOfRise: 0.12,
    projectionHoursToWarning: 0,
    projectionHoursToDanger: 6.5,
  },
  {
    id: "alert-fb-002",
    stationId: "fb-teesta-domohani",
    stationName: "Teesta at Domohani (Hill River)",
    place: "Jalpaiguri, West Bengal",
    kind: "River",
    riskScore: 56,
    category: "Warning",
    channel: "sms",
    sentTo: "+91-DEMO-CONTROL",
    body: "HDNS FLOOD ALERT — WARNING (56/100)\nStation: Teesta at Domohani\nLevel: 89.4 m | rise +0.08 m/h\nThresholds: warning 89.8 / danger 90.5 m\nStill rising — ~13.7h to danger level.\n──\nSent to DEMO list.",
    delivered: true,
    deliveredVia: "console-demo",
    deliveryState: "logged-console",
    createdAt: new Date(now - 32 * 60_000).toISOString(),
    acknowledgedAt: new Date(now - 10 * 60_000).toISOString(),
    acknowledgedBy: "NDRF Control Room (Demo)",
    level: 89.4,
    unit: "m",
    normalLevel: 88.0,
    warningLevel: 89.8,
    dangerLevel: 90.5,
    rateOfRise: 0.08,
    projectionHoursToWarning: 0,
    projectionHoursToDanger: 13.7,
  },
  {
    id: "alert-fb-003",
    stationId: "nwdp-arrah-chhapra-bridge",
    stationName: "Ganga at Arrah Chhapra Bridge",
    place: "Saran, Bihar · Bihar Water Dept",
    kind: "River",
    riskScore: 64,
    category: "Warning",
    channel: "email",
    sentTo: "bihar-sdma@demo.local",
    body: "HDNS FLOOD ALERT — WARNING (64/100)\nStation: Ganga at Arrah Chhapra Bridge\nLevel: 49.12 m | rise +0.075 m/h\nThresholds: warning 48.44 / danger 51.80 m\nStill rising — ~35.7h to danger level.\n──\nSent to Bihar SDMA demo list.",
    delivered: true,
    deliveredVia: "console-demo",
    deliveryState: "logged-console",
    createdAt: new Date(now - 45 * 60_000).toISOString(),
    acknowledgedAt: null,
    acknowledgedBy: null,
    level: 49.12,
    unit: "m",
    normalLevel: 45.07,
    warningLevel: 48.44,
    dangerLevel: 51.8,
    rateOfRise: 0.075,
    projectionHoursToWarning: 0,
    projectionHoursToDanger: 35.7,
  },
  {
    id: "alert-fb-004",
    stationId: "nwdp-nh15-crossing-fakirpara-tangni",
    stationName: "Brahmaputra at NH-15 Fakirpara Tangni",
    place: "Darrang, Assam · Assam Water Dept",
    kind: "River",
    riskScore: 44,
    category: "Watch",
    channel: "email",
    sentTo: "assam-sdma@demo.local",
    body: "HDNS ADVISORY — WATCH (44/100)\nStation: Brahmaputra at NH-15 Fakirpara Tangni\nLevel: 60.98 m | rise +0.040 m/h\nThresholds: warning 61.11 / danger 61.62 m.\n──\nSent to Assam SDMA demo list.",
    delivered: true,
    deliveredVia: "console-demo",
    deliveryState: "logged-console",
    createdAt: new Date(now - 60 * 60_000).toISOString(),
    acknowledgedAt: new Date(now - 18 * 60_000).toISOString(),
    acknowledgedBy: "Assam SDMA (Demo)",
    level: 60.98,
    unit: "m",
    normalLevel: 60.6,
    warningLevel: 61.11,
    dangerLevel: 61.62,
    rateOfRise: 0.04,
    projectionHoursToWarning: 3.25,
    projectionHoursToDanger: 16.0,
  },
];

export function getFallbackStats(): NationalStats {
  const scores = FALLBACK_STATIONS.map((s) => s.latest?.riskScore ?? 0);
  const byCategory = {
    Normal: 0,
    Watch: 0,
    Warning: 0,
    Severe: 0,
    Critical: 0,
    "No data": 0,
  };
  for (const s of FALLBACK_STATIONS) {
    if (s.latest) {
      byCategory[s.latest.category] = (byCategory[s.latest.category] ?? 0) + 1;
    }
  }
  return {
    nationalIndex: Math.round(scores.reduce((a, b) => a + b, 0) / scores.length),
    totalStations: FALLBACK_STATIONS.length,
    withReadings: FALLBACK_STATIONS.length,
    byCategory,
    updatedAt: new Date().toISOString(),
  };
}

export function getFallbackHistory(stationId: string, hours = 24): { points: HistoryPoint[]; stats: IntervalStats } {
  const st = FALLBACK_STATIONS.find((s) => s.id === stationId || s.externalId === stationId) ?? FALLBACK_STATIONS[0];
  const count = Math.min(hours, 48);
  const stepMs = (hours * 3600_000) / count;
  const points: HistoryPoint[] = Array.from({ length: count }).map((_, i) => {
    const t = now - (count - 1 - i) * stepMs;
    const v = Math.round((st.normalLevel + (i / count) * (st.latest?.level ? st.latest.level - st.normalLevel : 1)) * 100) / 100;
    const score = Math.round(20 + (i / count) * 45);
    return {
      t,
      v,
      riskScore: score,
      category: categoryFromScore(score),
    };
  });
  const vals = points.map((p) => p.v);
  return {
    points,
    stats: {
      label: `Last ${hours}h`,
      rateOfRise: st.latest?.rateOfRise ?? 0.05,
      min: Math.min(...vals),
      max: Math.max(...vals),
      avg: Math.round((vals.reduce((a, b) => a + b, 0) / vals.length) * 100) / 100,
      current: st.latest?.level ?? st.normalLevel,
      category: st.latest?.category ?? "Normal",
    },
  };
}
